
# Stage 1: Build the React app
FROM node:20-slim as build-stage

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the entire project to the container
COPY . .

# Build the React app
RUN npm run build



# Stage 2: Serve the React app with NGINX
FROM nginx:1.25-alpine as production-stage

# Copy the built React app from the previous stage to the NGINX server's default public directory
COPY --from=build-stage /app/frontend/build /usr/share/nginx/html

# Copy the NGINX configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the default NGINX port
EXPOSE 80

# Start NGINX when the container is run
CMD ["nginx", "-g", "daemon off;"]
