version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    restart: always
    networks:
      - kompare-app
    env_file: 
     - frontend/.env.production
    environment: 
     - prod
    depends_on:
    - backend

  backend:
    build: ./backend
    ports:
      - 4001:4000
    restart: always
    networks:
      - kompare-app
    env_file: 
      - backend/.env.production
    environment: 
     - prod
    depends_on:
      - database
    command: sh -c "npm run seedDb && npm run start:prod"

  database:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./mongo/data:/data/db
    networks:
      - kompare-app

networks:
  kompare-app:
    driver: bridge
